### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by Frostbyte0x70** [adakite1/skysongbuilder#2]
**Description of the bug**
I tried to import a midi + sf2 song that I ripped from another game using VgmTrans v1.1 and got an assertion error.

**Recordings**
The midi and sf2 files are attached, as well as the config file used.
[test.zip](https://github.com/adakite1/skysongbuilder/files/12686321/test.zip)

**Desktop**
 - OS: Windows
 - Version: The program doesn't specify this anywhere, but it should be 0.1.0.

**Comment by adakite1** [comment]
This assertion is for detecting when duplicate presets exist in the soundfont with the same shared bank/preset ids, which should never happen, but weirdly in this case while no duplicate presets can be seen from Polyphone, the library that I am using to parse the soundfont returns the following:
![image](https://github.com/adakite1/skysongbuilder/assets/88466388/6386293d-871f-4b33-bc43-d6959cad4316)
A second preset after all the normal ones with a bank/preset id of 000:000, and with no sample mappings inside, an empty preset. I'm not sure if this is due to a rule in the specs to ignore empty presets, but this seems like the most likely explanation. An interesting observation was that Polyphone opens the file correctly, and it also works in ssb after being re-exported from Polyphone.
Since the preset causing problems is empty, a filter stripping away any empty presets solves this problem, and future soundfonts containing empty preset should also be readable.
